apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: internalpod
  name: internalpod
  namespace: internal
spec:
  containers:
  - command:
    - /bin/bash
    - "-c"
    - "sleep 3600"
    image: ubuntu
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
